use_frameworks!

target 'PhotoViewControllerSwift_Example' do
  pod 'PhotoViewControllerSwift', :path => '../'

  target 'PhotoViewControllerSwift_Tests' do
    pod 'PhotoViewControllerSwift', :path => '../'

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
