# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild clean test -enableCodeCoverage YES -workspace Example/PhotoViewControllerSwift.xcworkspace -scheme PhotoViewControllerSwift-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty
- pod lib lint
